# Generated by Django 5.2.7 on 2026-01-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PUBLISHED', 'Published'), ('HIDDEN', 'Hidden')], default='PUBLISHED', max_length=20),
        ),
    ]
