# Generated by Django 5.2.10 on 2026-01-19 14:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo'),
        ),
    ]
